### ISSUE TITLE
Multiple configurations?

### ISSUE THREAD

**Issue by hopewise** [ueberauth/guardian#286] opened 2017-04-09 14:27 UTC
I am using my phoenix app to serve several end points, how can I have multiple config for Guardian? is this possible?

As there will be different issuer name for each endpoint.

Please advice, thank!

**Comment by scrogson** [comment] 2017-04-10 14:03
Hi @hopewise,

Thanks for submitting this issue. This is a duplicate of https://github.com/ueberauth/guardian/issues/258 so I will close. Feel free to join in the conversation there.

**Closed by scrogson** 2017-04-10 14:03 UTC
